### ISSUE TITLE
About HMC-QU dataset processing

### ISSUE THREAD

**Issue by Zehui-Lin** [xianlin7/SAMUS#15]
https://www.kaggle.com/datasets/aysendegerli/hmcqu-dataset

Dear author, thank you for your excellent work on open source. I have a question for you. I downloaded the dataset HMC-QU from the website kaggle. I found that the resolution of the original image and the segmented mask is not the same. The resolution of the original image is generally 422*636 (there are some others), while the resolution of the mask is 224*224. May I ask the author how you deal with it?

**Comment by xianlin7** [comment]
> https://www.kaggle.com/datasets/aysendegerli/hmcqu-dataset
> 
> Dear author, thank you for your excellent work on open source. I have a question for you. I downloaded the dataset HMC-QU from the website kaggle. I found that the resolution of the original image and the segmented mask is not the same. The resolution of the original image is generally 422_636 (there are some others), while the resolution of the mask is 224_224. May I ask the author how you deal with it?


After comparison, we resized these data and standardized them to 256 x 256.

**Comment by Zehui-Lin** [comment]
That is, directly resize 422*636 (or any other resolution) to 224*224?

**Comment by Zehui-Lin** [comment]
That is, directly resize 422\*636 (or any other resolution) to 224\*224?

**Comment by xianlin7** [comment]
> That is, directly resize 422*636 (or any other resolution) to 224*224?

256×256

**Comment by Philo-github** [comment]
Thank you for your explanation, but some detail questions still need you to give answers, the dataset gives gt size of 224*224 in mat format, and the given avi size is not 224*224, do you mean the adjustment is to resize the avi data directly to 224 or crop it to 224? Because these two operations will form different gt counterparts. Based on the experiment, my guess is avi(non-224)->(crop)->2D image(224)->(resize)->256.Hope I can get your answer!

**Comment by xianlin7** [comment]
All our data is directly resized to 256 x 256.
